In [10]:
import numpy as np

In [11]:
print('convert a list of numeric values into a 1D-array') 

original = [12.23, 13.32, 100, 36.32]
a = np.array(original)
print(a)

convert a list of numeric values into a 1D-array
[ 12.23  13.32 100.    36.32]


In [12]:
print('create a 3x3 matrix with values ranging from 2 to 10')

a = np.arange(2,11).reshape(3,3)
print(a)

create a 3x3 matrix with values ranging from 2 to 10
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [13]:
print('create a null vector of size 10 and update the sixth value to 11')

original = np.zeros(10)
print(original)
print()

# original[6] = 11
# print(original)
# print()

for n in range(0, len(original)):
    if n == 6:
        original[n] = 11
        break
print(original)

create a null vector of size 10 and update the sixth value to 11
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [14]:
print('create an 8x8 matrix and fill it with a checkerboard pattern')

x = np.zeros((8, 8), dtype=int)
#setting alternate rows starting from the 2nd row with alt. columns to 1
x[1::2, ::2] = 1

#setting alternate rows starting from the 1st row with alt. columns to 1
x[::2, 1::2] = 1

print(x)

create an 8x8 matrix and fill it with a checkerboard pattern
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [15]:
print('create an 8x8 matrix and fill it with a checkerboard pattern')

x = np.ones((8, 8), dtype=int)
#setting alternate rows starting from the 2nd row with alt. columns to 1
x[1::2, ::2] = 0

#setting alternate rows starting from the 1st row with alt. columns to 1
x[::2, 1::2] = 0

print(x)

create an 8x8 matrix and fill it with a checkerboard pattern
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [16]:
print('test whether each element is also present in a second array')

array1 = np.array([0, 10, 20, 40, 60])
array2 = [0, 40]

print(np.in1d(array1, array2))

test whether each element is also present in a second array
[ True False False  True False]


In [17]:
print('find common values between two arrays')

array1 = np.array([0, 10, 20, 40, 60])
array2 = [10, 30, 40]

print(np.intersect1d(array1, array2))

find common values between two arrays
[10 40]


In [18]:
print('get the unique elements of an array')

x = np.array([10, 10, 20, 20, 30, 30])
print(np.unique(x))
print()

y = np.array([[1, 1], [2, 3]])
print(np.unique(y))

get the unique elements of an array
[10 20 30]

[1 2 3]


In [19]:
print('create a contiguous flattened array')

x = np.array([[10, 20, 30], [20, 40, 50]])
print(x)
print()

y = np.ravel(x)
print(y)
print()

create a contiguous flattened array
[[10 20 30]
 [20 40 50]]

[10 20 30 20 40 50]



In [20]:
print('create another shape from an array without changing its data')

x = np.array([1, 2, 3, 4, 5, 6])
print(x)
print()

y = np.reshape(x, (3,2))
print(y)
print()

z = y.transpose()
print(z)


create another shape from an array without changing its data
[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]

[[1 3 5]
 [2 4 6]]


In [21]:
a = np.full((3,5), 2)
print(a)
print()

b = np.ones((3,5)) * 2
print(b)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [22]:
x = np.eye(3)
print(x)
print()

y = np.diag([1, 1, 1])
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [23]:
print('create an array like two triangles of 0s and 1s')

#generating a lower-triangular matrix of size 4x3
#with ones on and below the main diagonal shifted by -1
x = np.tri(4, 3, -1)
print(x) 

create an array like two triangles of 0s and 1s
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [24]:
print('find the 4th element')

x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
print()

e1 = x.flat[3]
print(e1) 

find the 4th element
[[ 2  4  6]
 [ 6  8 10]]

6


In [25]:
print('convert 1-D arrays as columns into a 2-D array')

a = np.array((10, 20, 30))
b = np.array((40, 50, 60))

#stacking arrays 'a' and 'b' as columns
c = np.column_stack((a, b))

print(c)

convert 1-D arrays as columns into a 2-D array
[[10 40]
 [20 50]
 [30 60]]


In [26]:
x = np.zeros((5,5))
print(x)
print()

x += np.arange(5)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [27]:
print('sum all the multiples of 3 or 5 below 100')

x = np.arange(1, 100)

#finding numbers in the array that are multiples of 3 OR 5
n = x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:100])
print(n.sum())
print()

#finding numbers in the array that are multiples of 3 AND 5
n = x[(x % 3 == 0) & (x % 5 == 0)]
print(n[:100])
print(n.sum())

sum all the multiples of 3 or 5 below 100
[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318

[15 30 45 60 75 90]
315


In [28]:
print('create range of 0 to 1000')
x = np.arange(1e3)
print(x)

create range of 0 to 1000
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.
  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.
  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.
  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
  98.  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111.
 112. 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125.
 126. 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139.
 140. 141. 142. 143. 144. 145. 146. 147. 148. 149. 150. 151. 152. 153.
 154. 155. 156. 157. 158. 159. 160. 161. 162. 163. 164. 165. 166. 167.
 168. 169. 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180. 181.
 182. 183. 184. 185. 186. 187. 188. 189. 190. 191. 