In [3]:
import numpy as np

In [4]:
print('ex1: generate five random numbers from the normal distribution')

x = np.random.normal(size=5)
print(x)

ex1: generate five random numbers from the normal distribution
[ 0.05662663 -0.05561061  0.08613881 -0.38761177  0.17768348]


In [5]:
print('ex2: generate six random integers between 10 and 30')

def generate_random(start, end, n):
    return np.random.randint(start, end, size=n)

print(generate_random(10, 30, 6))

ex2: generate six random integers between 10 and 30
[12 27 17 11 11 18]


In [6]:
print('ex3: create a 3x3x3 array with random values')

def generate_random(tpl=(3,3,3)):
    return np.random.rand(*tpl)

print(generate_random())

ex3: create a 3x3x3 array with random values
[[[0.89572696 0.38507849 0.51995593]
  [0.5064341  0.91714836 0.58480242]
  [0.64522859 0.57232905 0.49431498]]

 [[0.93125245 0.46112238 0.67677259]
  [0.08423816 0.99182777 0.0588189 ]
  [0.70698116 0.9241159  0.96503342]]

 [[0.60329652 0.57366886 0.26464323]
  [0.31924603 0.01961842 0.17097836]
  [0.93425162 0.08056245 0.17090766]]]


In [7]:
print('ex4: create a 5x5 array with random values and find the minimum and maximum values')

def generate_random(tpl=(5,5)):
    result = np.random.rand(*tpl)
    return result, np.max(result), np.min(result) #--> can use array.max() and array.min()
    
print(generate_random())

ex4: create a 5x5 array with random values and find the minimum and maximum values
(array([[0.15488435, 0.81477847, 0.31692714, 0.03304263, 0.25325881],
       [0.23372879, 0.50252544, 0.3349234 , 0.19990635, 0.0018494 ],
       [0.31084631, 0.86582107, 0.59894137, 0.66414627, 0.54578015],
       [0.01602403, 0.50496595, 0.59848298, 0.11329012, 0.57558403],
       [0.01512799, 0.84181167, 0.48398736, 0.42541924, 0.2073384 ]]), 0.8658210653648334, 0.0018494048889495796)


In [8]:
print('ex5: create a random 10x4 array and extract the first five rows of the array and store them into a variable')

r = np.round(np.random.rand(10, 4), 2)
e = r[0:5] #--> x[:5, :]
print(r)
print()
print(e)
print()

ex5: create a random 10x4 array and extract the first five rows of the array and store them into a variable
[[0.68 0.19 0.95 0.48]
 [0.45 0.57 0.9  0.3 ]
 [0.46 0.78 0.81 0.5 ]
 [0.06 0.3  0.51 0.9 ]
 [0.99 0.95 0.35 0.9 ]
 [0.32 0.05 0.62 0.18]
 [0.25 0.82 0.71 0.16]
 [0.26 0.01 0.19 0.47]
 [0.78 0.34 0.13 0.83]
 [0.39 0.   0.65 0.58]]

[[0.68 0.19 0.95 0.48]
 [0.45 0.57 0.9  0.3 ]
 [0.46 0.78 0.81 0.5 ]
 [0.06 0.3  0.51 0.9 ]
 [0.99 0.95 0.35 0.9 ]]



In [9]:
print('ex6: shuffle numbers between 0 and 10 (inclusive)')

s = np.arange(10)
print(s)
print()

p = np.random.permutation(s)
print(p)

ex6: shuffle numbers between 0 and 10 (inclusive)
[0 1 2 3 4 5 6 7 8 9]

[9 3 5 6 0 4 8 1 2 7]


In [10]:
print('ex7: normalize a 3x3 random matrix')

r = np.random.rand(3,3)
print(r)
print()

#finding the maximum and minimum values in array
rmax, rmin = np.max(r), np.min(r)

#normalizing the array using min-max scaling: (x - xmin) / (xmax - xmin)
r = (r - rmin) / (rmax - rmin)
print(r)

ex7: normalize a 3x3 random matrix
[[0.31397181 0.36213415 0.78422775]
 [0.14069365 0.5991535  0.18864338]
 [0.289868   0.08151719 0.47685787]]

[[0.33079711 0.39933505 1.        ]
 [0.08421171 0.73662805 0.1524471 ]
 [0.29649591 0.         0.56259391]]


In [11]:
print('ex8: create a random vector of size 10 and sort it')

r = np.random.rand(10)
print(r)
print()

r.sort()
print(r)

ex8: create a random vector of size 10 and sort it
[0.47573435 0.9146825  0.99169695 0.19618936 0.43031275 0.34497731
 0.81363465 0.53814268 0.73239203 0.39689939]

[0.19618936 0.34497731 0.39689939 0.43031275 0.47573435 0.53814268
 0.73239203 0.81363465 0.9146825  0.99169695]


In [12]:
print('ex9: find the nearest value from a given value in an array')

#generating an array of 5 random numbers between 1 and 12
x = np.round(np.random.uniform(1, 10, 5), 5)
print(x)
print()

v = 4

#finding the value 'n' in 'x' that is closest to 'v'
#using np.abs(x - v).argmin() to get the index of the element in 'x' closest to 'v'
#accessing the element using x.flat[index] to get the closest value 'n'
n = x.flat[np.abs(x - v).argmin()]
print(n)

ex9: find the nearest value from a given value in an array
[3.36708 1.50051 3.50726 3.13025 4.53673]

3.50726


In [13]:
print('ex10: check two random arrays are equal or not')

x = np.arange(5)
y = np.arange(5)
array_equal = np.allclose(x, y)
print(x == y)
print(array_equal)
print()

i = np.random.randint(0, 2, size=(3,3))
j = np.random.randint(0, 2, size=(3,3))
array_equal = np.allclose(i, j)
print(i == j)
print(array_equal)

ex10: check two random arrays are equal or not
[ True  True  True  True  True]
True

[[ True  True False]
 [ True  True False]
 [False  True  True]]
False


In [14]:
print('ex11: create random vector replace the maximum /minimum value')

def max_vector(n, set_new_max):
    v = np.round(np.random.rand(n), 7)
    v[v.argmax()] = set_new_max
    return v
    
print(max_vector(15, -1))
print()

def min_vector(n, set_new_min):
    v = np.round(np.random.rand(n), 7)
    v[v.argmin()] = set_new_min
    return v
    
print(min_vector(5, 0))

ex11: create random vector replace the maximum /minimum value
[ 0.1239918  0.9429879  0.0519396  0.6342072  0.2099639  0.9190388
  0.0249168  0.124334   0.8535022 -1.         0.0543346  0.7538676
  0.2191755  0.1127039  0.9281485]

[0.5310053 0.8439316 0.5088689 0.        0.8528245]


In [15]:
print('ex12: find point by point distances of a random vector with shape (10,2) representing coordinates')

a = np.random.random((10, 2))

#extracting x and y coordinates from the array 'a' using np.atleast_2d() method
#at least 2-dimensional arrays from the columns of 'a'
x, y = np.atleast_2d(a[:, 0], a[:, 1])

#calculating the Euclidean distance between points in the 'a' array using the formula:
#d = sqrt((x - x_transpose)^2 + (y - y_transpose)^2)
#where x and y are the coordinate matrices created, and T is the transpose of those matrices
d = np.sqrt((x - x.T) ** 2 + (y - y.T) ** 2)

print(d)

ex12: find point by point distances of a random vector with shape (10,2) representing coordinates
[[0.         0.86180007 0.91301225 0.90110104 1.00105418 0.39660052
  1.23360595 0.61968419 0.82432621 0.78097208]
 [0.86180007 0.         0.05667949 0.21932685 0.24912157 0.50660546
  0.50486906 0.25521406 0.12055156 0.2567023 ]
 [0.91301225 0.05667949 0.         0.19778569 0.25433441 0.56237737
  0.45499137 0.2999131  0.16709874 0.30381365]
 [0.90110104 0.21932685 0.19778569 0.         0.45194233 0.61275964
  0.34500419 0.29891975 0.3357232  0.46614129]
 [1.00105418 0.24912157 0.25433441 0.45194233 0.         0.60931326
  0.6524062  0.46232379 0.193514   0.2299104 ]
 [0.39660052 0.50660546 0.56237737 0.61275964 0.60931326 0.
  0.95747154 0.31598086 0.44401285 0.38525033]
 [1.23360595 0.50486906 0.45499137 0.34500419 0.6524062  0.95747154
  0.         0.6438294  0.6220621  0.75879252]
 [0.61968419 0.25521406 0.2999131  0.29891975 0.46232379 0.31598086
  0.6438294  0.         0.26976231 0.

In [16]:
print('ex13: find the most frequent value in an array')
import statistics

s = np.random.randint(1, 10, size=15)
print(s)
print()

frequent = statistics.mode(s)
most_frequent_value = np.bincount(s).argmax()
print(frequent, most_frequent_value, sep=', ')

ex13: find the most frequent value in an array
[5 3 3 8 4 9 1 8 1 7 9 2 1 2 9]

9, 1


In [17]:
print('ex14: convert cartesian coordinates to polar coordinates of a random 10x2 matrix representing cartesian coordinates')

z = np.random.random((10,2))

x, y = z[:, 0], z[:, 1]

#calculating the Euclidean distance (r) using the formula sqrt(x^2 + y^2)
r = np.sqrt(x**2 + y**2)

#calculating the angles (t) using arctan2() function, which returns the arctangent of y/x in radians
t = np.arctan2(y, x)

#displaying the calculated Euclidean distances (r)
print(r)
print()

#displaying the calculated angles (t) in radians
print(t)

ex14: convert cartesian coordinates to polar coordinates of a random 10x2 matrix representing cartesian coordinates
[0.90612409 1.11784626 0.31575743 0.53423837 0.93201836 0.12201907
 1.18865935 0.26822523 0.79452285 0.91035805]

[0.81759647 0.79013706 1.01613211 1.13629192 1.1773083  0.01050238
 0.60791792 0.93045231 0.75405793 0.27044605]


In [18]:
print('ex15: find the closest value (to a given scalar) in an array')

i = np.arange(100)
f = np.random.uniform(0, 100)

#finding the index of the element in array closest to the generated value
index = (np.abs(i - f)).argmin()

print(i[index])

ex15: find the closest value (to a given scalar) in an array
58


In [19]:
print('ex16: get the n largest values of an array')

x = np.arange(10)
print(x, np.max(x), sep='\n')
print()

print('alternatively')
np.random.shuffle(x)

#selecting the 'n' largest elements in 'x' using argsort and slicing
n = 1
print(x[np.argsort(x)[-n:]])

ex16: get the n largest values of an array
[0 1 2 3 4 5 6 7 8 9]
9

alternatively
[9]


In [20]:
print('ex17: create a three-dimension array with shape (300, 400, 5) and set to a variable, \
fill the array elements with values using unsigned integer (0 to 255)')

#setting the random seed to 32 for reproducibility
np.random.seed(32)

nums = np.random.randint(low=0, high=256, size=(300, 400, 5), dtype=np.uint8)

print(nums)

ex17: create a three-dimension array with shape (300, 400, 5) and set to a variable, fill the array elements with values using unsigned integer (0 to 255)
[[[215  42 224 219  43]
  [166  69  15 133 255]
  [105  95  54  37 201]
  ...
  [240  22  66 232 132]
  [ 13  85  53 220 170]
  [249  62 221 146  69]]

 [[ 73  79 148 132 164]
  [  3  93  98 138 200]
  [174  34  31 208 130]
  ...
  [ 15 252  41  64  39]
  [188 216 223 124  27]
  [ 85 112 240 116 231]]

 [[227  50 243  20 171]
  [ 12  66 108 102  63]
  [107  54   0   0 173]
  ...
  [215  46  57  99 151]
  [243 199  31  28 179]
  [143   7  30 175 190]]

 ...

 [[214  64  64 212  62]
  [140  44 217  17 164]
  [226 146 247  53 199]
  ...
  [189  68  49 117  63]
  [ 14  17 109  82  92]
  [155 221 135 184 231]]

 [[132 194 160 136 102]
  [132 244 230 117 181]
  [146 245  21 164  29]
  ...
  [125 240 243 190 240]
  [137  41 157 117 155]
  [ 20  92  72 182  41]]

 [[120  45 198 218 190]
  [ 42 150 190 103 106]
  [164  71 220 114  59]
  ...
 