In [2]:
import numpy as np

Exercise 1: sort a given array of shape 2 along the first axis, last axis and on flattened array

In [3]:
print('sort a given array of shape 2 along the first axis, last axis and on flattened array')
a = np.array([[10, 40], [30, 20]])

#along the first axis
print(np.sort(a, axis=0))
print()

#along the last axis (axis=-1, default behavior)
print(np.sort(a, axis=-1))
print()

#sorting the flattened array
print(np.sort(a, axis=None))
print()

sort a given array of shape 2 along the first axis, last axis and on flattened array
[[10 20]
 [30 40]]

[[10 40]
 [20 30]]

[10 20 30 40]



Exercise 2: create a structured array from given student name, height, class and their data types

In [4]:
print('create a structured array from given student name, height, class and their data types')
#Now sort the array on height.
a = np.array([('James', 5, 48.5), ('Nail', 6, 52.5), ('Paul', 5, 42.1), ('Pit', 5, 40.11)])

print(a)
print()

print(sorted(a, key=lambda x: x[-1]))
print()

x = list(a)
print(sorted(x, key=lambda x: x[-1]))

create a structured array from given student name, height, class and their data types
[['James' '5' '48.5']
 ['Nail' '6' '52.5']
 ['Paul' '5' '42.1']
 ['Pit' '5' '40.11']]

[array(['Pit', '5', '40.11'], dtype='<U32'), array(['Paul', '5', '42.1'], dtype='<U32'), array(['James', '5', '48.5'], dtype='<U32'), array(['Nail', '6', '52.5'], dtype='<U32')]

[array(['Pit', '5', '40.11'], dtype='<U32'), array(['Paul', '5', '42.1'], dtype='<U32'), array(['James', '5', '48.5'], dtype='<U32'), array(['Nail', '6', '52.5'], dtype='<U32')]


Exercise 2-3: create a structured array from given student name, height, class and their data types

In [5]:
print('create a structured array from given student name, height, class and their data types')

data_type = [('name', 'S15'), ('class', int), ('height', float)]

students_details = [('James', 5, 48.5), ('Nail', 6, 52.5), ('Paul', 5, 42.10), ('Pit', 5, 40.11)]

students = np.array(students_details, dtype=data_type)

print(np.sort(students, order=['height']))
print(np.sort(students, order=['class', 'height']))
print(np.sort(students, order=['name']))

create a structured array from given student name, height, class and their data types
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]


Exercise 4: sort the student id with increasing height of the students from given students id and height

In [6]:
print('sort the student id with increasing height of the students from given students id and height')

student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])

#sorting the indices based on 'id' and 'height'
indices = np.lexsort((student_id, student_height))

print(indices)
print()

for n in indices:
    print(student_id[n], student_height[n])

sort the student id with increasing height of the students from given students id and height
[4 0 5 3 6 1 2]

1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


Exercise 5: get the indices of the sorted elements of a given array

In [7]:
print('get the indices of the sorted elements of a given array')

student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

#sorting the indices of the array's elements in ascending order
i = np.argsort(student_id)

print(i)

get the indices of the sorted elements of a given array
[0 3 4 6 1 5 2]


Exercise 6: sort a given complex array using the real part first, then the imaginary part

In [8]:
print('sort a given complex array using the real part first, then the imaginary part')

complex_num = [1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j]

#sorting the given complex array using the real part first, then the imaginary part
print(np.sort_complex(complex_num))

sort a given complex array using the real part first, then the imaginary part
[1.+2.j 3.-2.j 3.-1.j 3.+5.j 4.-3.j]


Exercise 7: partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order

In [9]:
print('partition a given array in a specified position and move all the smaller elements values \
to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice)')

nums = np.array([70, 50, 20, 30, -11, 60, 50, 40])

#partitioning the array at the 4th position
print(np.partition(nums, 4))

partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice)
[-11  30  20  40  50  50  60  70]


Exercise 8: sort the specified number of elements from beginning of a given array

In [10]:
print('sort the specified number of elements from beginning of a given array')

nums = np.random.rand(10)

#sorting the first 5 elements using argpartition
print(nums[np.argpartition(nums, range(5))])

sort the specified number of elements from beginning of a given array
[0.08171024 0.11699795 0.42195286 0.42233786 0.44597126 0.6706194
 0.98789453 0.85166811 0.49896633 0.91477943]


Exercise 9: sort an given array by the nth column

In [11]:
print('sort an given array by the nth column')

nums = np.random.randint(0, 10, (3, 3))

print(nums[nums[:, 1].argsort()])

sort an given array by the nth column
[[1 1 4]
 [1 7 4]
 [7 8 9]]
