In [2]:
import numpy as np

In [3]:
print('compute the multiplication of two given matrixes')

a = np.array([[1, 0], [0, 1]])
b = np.array([[1, 2], [3, 4]])

print(np.dot(a,b))

compute the multiplication of two given matrixes
[[1 2]
 [3 4]]


In [4]:
print('compute the outer produce of two given vectors')

p = np.array([[1, 0], [0, 1]])
q = np.array([[1, 2], [3, 4]])

print(np.outer(p, q))

compute the outer produce of two given vectors
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


In [5]:
print('compute the cross product of two given vectors')

p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]

result1 = np.cross(p, q)
result2 = np.cross(q, p)

print(result1, result2, sep='\n')

compute the cross product of two given vectors
[ 2 -3]
[-2  3]


In [6]:
print('compute the determinant of a square array')

a = np.array([[1, 0], [1, 2]])
print(np.linalg.det(a)) 

compute the determinant of a square array
2.0


In [7]:
print("evaluate Einstein’s summation convention of two given multidimensional arrays")

a = np.array([1,2,3])
b = np.array([0,1,0])

#compute the Einstein’s summation convention of the 1-D arrays
result =  np.einsum("n,n", a, b)
print(result)
print()


x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)

result = np.einsum("mk,kn", x, y)
print(result)

evaluate Einstein’s summation convention of two given multidimensional arrays
2

[[ 24  27  30]
 [ 78  90 102]
 [132 153 174]]


In [8]:
print('compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension')

a = np.array([1, 2, 5])
b = np.array([2, 1, 0])

result = np.inner(a, b)
print(result)
print()

x = np.arange(9).reshape(3, 3)
y = np.arange(3, 12).reshape(3, 3)

result = np.inner(x, y)
print(result) 

compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension
4

[[ 14  23  32]
 [ 50  86 122]
 [ 86 149 212]]


In [9]:
print('compute the inverse of a given matrix')

m = np.array([[1,2], [3,4]])

result =  np.linalg.inv(m)
print(result)

compute the inverse of a given matrix
[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
print('compute the sum of the diagonal element of a given array')

m = np.arange(6).reshape(2, 3)

#calculate the trace of the matrix 'm' using np.trace() function
result = np.trace(m)
print(result)

compute the sum of the diagonal element of a given array
4
