In [2]:
import numpy as np

FIND MIN AND MAX DISTANCE OF MULTIPLE VECTORS

In [3]:
def min_max_dist(*vectors):
    length = len(vectors) #how many vectors to begin with?
    dist_lst = [] #input the distance between vectors
    v_range = list(range(0, len(vectors))) #no of vectors to work with
    index = 0
    while index < length:
        for v in vectors:
            base_vector = vectors[0]
            distance = np.linalg.norm(base_vector-vectors[index]) #calculate vector distance
            dist_lst.append(distance)
            index += 1
    dist_lst.remove(0.0) #for instances when distance is vector by itself
    print(min(dist_lst), max(dist_lst))

vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
vec3 = np.array([7, 8, 9])
vec4 = np.array([10, 11, 12])
vec5 = np.array([13, 14, 15])

min_max_dist(vec1, vec2, vec3, vec4, vec5)
print()

min_max_dist(vec3, vec1)

5.196152422706632 20.784609690826528

10.392304845413264 10.392304845413264


IF ONE PAIR OF VECTORS IS PERPENDICULAR

In [4]:
def any_normal(*vectors):
    length = len(vectors) #how many vectors to begin with?
    scar_prod_lst = [] #input the scalar product between vectors
    index = 0
    while index < length:
        for v in vectors:
            base_vector = vectors[0]
            scalar_product = np.dot(base_vector, vectors[index])
            scar_prod_lst.append(scalar_product)
            index += 1
    if 0 in scar_prod_lst:
        return True
    else:
        return False

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3, 4])
vec4 = np.array([-1, 5])

print(any_normal(vec1, vec2, vec3, vec4))
print(any_normal(vec2, vec3))

True
False


In [5]:
def get_loto(num):
    population = np.arange(0, 101)
    rand_repeat_select = np.random.choice(population, size=(num, 5, 5), replace=True)
    print(rand_repeat_select)
    
get_loto(3)
print()


def get_unique_loto(num):
    population = np.arange(0, 101)
    rand_unique_select = np.random.choice(population, size=(num, 5, 5), replace=False)
    print(rand_unique_select)

get_unique_loto(2)
print()

[[[ 31  12  20  97  43]
  [ 15  11  93  23  32]
  [ 94  93   5  46  61]
  [ 24  74  79  51  18]
  [ 27  59  42  66  80]]

 [[ 33  54  13  23  70]
  [ 36  76  75  81  50]
  [ 31  46  39  35  96]
  [ 40  66  51  84  96]
  [ 52  46  20  70  17]]

 [[ 55  29  41  17  85]
  [ 25  63   5  28  19]
  [ 26  14  10  76  89]
  [ 77  70  24 100   7]
  [ 12  94  86  78  41]]]

[[[82  2 64  7 35]
  [57 21 61 43 96]
  [29 68 88  1 90]
  [31 97 46 80  0]
  [26 20 91 23 32]]

 [[76 51 73  4 50]
  [93 41 78 53 85]
  [59 86 39  5 81]
  [58 15 17 71 56]
  [24 44 60 98 30]]]



In [6]:
def get_unique_loto(num):
    unique_loto = np.zeros((num, 5, 5), dtype=np.uint8)
    population = np.array(range(1, 101))
    for x in range(0, num):
        loto = np.random.choice(population, size=25, replace=False).reshape((5, 5))
        unique_loto[x] = loto
    return(unique_loto)

get_unique_loto(4)
print(np.shape(get_unique_loto(4)))

get_unique_loto(10)
print(np.shape(get_unique_loto(10)))

(4, 5, 5)
(10, 5, 5)


In [7]:
arr = np.arange(6)
print(arr)
print()

print(np.random.shuffle(arr))
print()

print(arr)
print()



playlist = ['Linkin Park', 'ACDC', 'Deep Purple']
print(playlist)
print()

shuffled = np.random.permutation(playlist)
print(shuffled)
print()

print(np.random.permutation(10))
print()



workers = ['Zlata', 'Yulia', 'Tanya M', 'Tanya V', 'Kristina']
unlucky_stay = np.random.choice(workers, size=1, replace=False)
print(unlucky_stay)
print()

unlucky_multiple = np.random.choice(workers, size=7, replace=True)
print(unlucky_multiple)
print()

choice = np.random.choice([1, 2, 3, 4, 5, 6], size=10)
print(choice)
print()



print(np.random.seed(23))
print(np.random.randint(10, size=(3,4)))
print()

np.random.seed(100)
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print()

[0 1 2 3 4 5]

None

[3 1 5 0 2 4]

['Linkin Park', 'ACDC', 'Deep Purple']

['Deep Purple' 'Linkin Park' 'ACDC']

[5 9 8 4 1 6 2 0 7 3]

['Zlata']

['Yulia' 'Yulia' 'Yulia' 'Kristina' 'Zlata' 'Tanya M' 'Zlata']

[4 1 6 2 1 2 2 5 2 6]

None
[[3 6 8 9]
 [6 8 7 9]
 [3 6 1 2]]

[8 8 3]
[7 7 0]
[4 2 5]

