In [1]:
from collections import Counter, defaultdict, OrderedDict

In [2]:
from functools import reduce

import itertools
from itertools import chain

In [3]:
import math
import statistics

In [4]:
import numpy as np
import pandas as pd

In [5]:
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
import plotly.express as px
import plotly.graph_objects as go

In [6]:
from chardet.universaldetector import UniversalDetector

In [7]:
import json
from pprint import pprint

In [8]:
import requests
from bs4 import BeautifulSoup
import schedule
import time

In [9]:
x = '5'
y = 'tyt'
z = '7ofhearts'

print(x.isdigit())
print(y.isalpha())
print(z.isalnum())

True
True
True


In [10]:
x = 'x'
y = 97
print(ord(x), chr(y))

120 a


LIST METHODS

In [11]:
x = [1, 2, 3]
y = [4, 5, 6]
t = [5, 6]
z = ['jackie', 'shauna', 'lottie']
w = [True, 'clue', 11]

In [12]:
x.append(y)
print(x)
print()

x.clear()
print(x)
print()

print(y.count(5))
print()

print(max(y))
print(min(y))
print()

y.extend(t)
print(y)
print()

print(sum(y))
print()

w.reverse()
print(w)
print()

w.remove(True)
print(w)
print()

w.pop(0)
print(w)
print()

w.insert(1, 'five')
print(w)

[1, 2, 3, [4, 5, 6]]

[]

1

6
4

[4, 5, 6, 5, 6]

26

[11, 'clue', True]

[11, 'clue']

['clue']

['clue', 'five']


TUPLE METHODS

In [13]:
x = (1, 2, 3)
y = ('leah', 'gretchen', 'seth')
z = ('jackie', 'nat', 'lottie', 'laura lee')

In [14]:
print(x.count(2))
print()

print(y.index('leah'))
print(y)
print()

print(tuple(zip(y, z)))
print()

1

0
('leah', 'gretchen', 'seth')

(('leah', 'jackie'), ('gretchen', 'nat'), ('seth', 'lottie'))



SET METHODS

In [15]:
x = {1, 2, 3}
y = {'leah', 'gretchen', 'seth'}
z = {'fatin', 'dot', 'martha'}

In [16]:
y.add('daniel')
print(y)
print()

v = {'nora'}
y.update(v)
print(y)
print()

{'seth', 'gretchen', 'leah', 'daniel'}

{'nora', 'leah', 'seth', 'gretchen', 'daniel'}



In [17]:
y.discard('nora')
print(y)
print()

{'leah', 'seth', 'gretchen', 'daniel'}



In [18]:
print(y.union(z))

{'fatin', 'martha', 'leah', 'dot', 'seth', 'gretchen', 'daniel'}


DICTIONARY METHODS

In [19]:
players = {
    'hearts': ['leah'],
    'clubs': ['fatin', 'dot', 'martha'],
    'diamonds': ['shelby', 'nora'],
    'spades': ['rachel', 'toni']
}

citizens = {
    'hearts': ['gretchen', 'daniel', 'seth'],
    'clubs': ['audrey', 'alex'],
    'diamonds': ['leonard', 'linh'],
    'spades': ['']
}

dealers = {
    'hearts': ['devon'],
    'clubs': ['josh'],
    'diamonds': ['susan', 'thom'],
    'spades': ['']
}

In [20]:
print(players.keys())
print(citizens.values())
print(players.items())
print()

dealers.clear()
print(dealers)
print()

x = players.get('hearts')
print(x)
print()

citizens.pop('clubs')
print(citizens)
print()


dict_keys(['hearts', 'clubs', 'diamonds', 'spades'])
dict_values([['gretchen', 'daniel', 'seth'], ['audrey', 'alex'], ['leonard', 'linh'], ['']])
dict_items([('hearts', ['leah']), ('clubs', ['fatin', 'dot', 'martha']), ('diamonds', ['shelby', 'nora']), ('spades', ['rachel', 'toni'])])

{}

['leah']

{'hearts': ['gretchen', 'daniel', 'seth'], 'diamonds': ['leonard', 'linh'], 'spades': ['']}



In [21]:
from collections import defaultdict

d = {}

players_x = {
    'hearts': ['leah'],
    'clubs': ['fatin', 'dot', 'martha'],
    'diamonds': ['shelby', 'nora'],
    'spades': ['rachel', 'toni']
}

citizens_x = {
    'hearts': ['gretchen', 'daniel', 'seth'],
    'clubs': ['audrey', 'alex'],
    'diamonds': ['leonard', 'linh'],
    'spades': ['']
}

for k1, v1 in players_x.items():
    for k2, v2 in citizens_x.items():
        if k1 not in d:
            d[k1] = v1 + v2
print(d)

{'hearts': ['leah', 'gretchen', 'daniel', 'seth'], 'clubs': ['fatin', 'dot', 'martha', 'gretchen', 'daniel', 'seth'], 'diamonds': ['shelby', 'nora', 'gretchen', 'daniel', 'seth'], 'spades': ['rachel', 'toni', 'gretchen', 'daniel', 'seth']}


In [22]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
test_series_1 = pd.Series([
    'Опыт работы 8 лет 3 месяца',
    'Опыт работы 3 года 5 месяцев',
    'Опыт работы 1 год 9 месяцев',
    'Опыт работы 3 месяца',
    'Опыт работы 6 лет'
])
test_series_1

0      Опыт работы 8 лет 3 месяца
1    Опыт работы 3 года 5 месяцев
2     Опыт работы 1 год 9 месяцев
3            Опыт работы 3 месяца
4               Опыт работы 6 лет
dtype: object

CONTAINS FUNCTION USED WITH STR

In [24]:
def get_experience(arg):
    #convert the string into a list with each element separated
    arg_lst = arg.split(' ')
    #for the experience in years AND months
    if len(arg_lst) == 6:
        yrs = arg_lst[2]
        mths = arg_lst[4]
        exp = (int(yrs) * 12) + int(mths)
    #for the experience in months OR years
    elif len(arg_lst) == 4:
        for word in arg_lst:
            if arg.__contains__('мес'):
                mths = arg_lst[2]
                exp = int(mths)
            elif arg.__contains__('лет') or arg.__contains__('год'):
                yrs = arg_lst[2]
                exp = int(yrs) * 12
    return exp

DROP COLUMNS

In [25]:
customer_df = pd.DataFrame({
            'number': [0, 1, 2, 3, 4],
            'cust_id': [128, 1201, 9832, 4392, 7472],
            'cust_age': [13, 21, 19, 21, 60],
            'cust_sale': [0, 0, 0.2, 0.15, 0.3],
            'cust_year_birth': [2008, 2000, 2002, 2000, 1961],
            'cust_order': [1400, 14142, 900, 1240, 8430]
        })

customer_df2 = pd.DataFrame({
            'number2': [0, 1, 2, 3, 4],
            'cust_id2': [128, 1201, 9832, 4392, 7472],
            'cust_age2': [13, 21, 19, 21, 60],
            'cust_sale2': [0, 0, 0.2, 0.15, 0.3],
            'cust_year_birth2': [2008, 2000, 2002, 2000, 1961],
            'cust_order2': [1400, 14142, 900, 1240, 8430]
        })

def delete_columns(df, col=[]):
    #work with a copy of the dataframe directly -> highly important otherwise leads to errors
    new_df = df
    #find whether the name of the column exists in the list
    for column in col:
        #if the name exists in the column names
        if column in df.columns: #-> no need to use the list()
            #delete the column 
            new_df = new_df.drop(column, axis=1, errors='ignore') #-> work directly with new_df entire time
        else:
            #if name of the column doesn't exist
            return None
    return new_df

print('first time')
print(delete_columns(df = customer_df, col = ['number']))
print()

print('second time')
print(delete_columns(col = ['cust_sale2', 'cust_age2'], df = customer_df2))
print()

print('third time')
print(delete_columns(df = customer_df2, col = ['cust_sale2', 'non-existent']))
print()

first time
   cust_id  cust_age  cust_sale  cust_year_birth  cust_order
0      128        13       0.00             2008        1400
1     1201        21       0.00             2000       14142
2     9832        19       0.20             2002         900
3     4392        21       0.15             2000        1240
4     7472        60       0.30             1961        8430

second time
   number2  cust_id2  cust_year_birth2  cust_order2
0        0       128              2008         1400
1        1      1201              2000        14142
2        2      9832              2002          900
3        3      4392              2000         1240
4        4      7472              1961         8430

third time
None

