In [1]:
import numpy as np
import pandas as pd

EXERCISE 10.6: CHESSBOARD

In [2]:
def get_chess(a):
    arr = np.zeros((a, a))
    arr[1::2, ::2] = 1
    arr[::2, 1::2] = 1
    return arr

EX10.8: FIND MIN AND MAX DISTANCE BETWEEN MULTIPLE VECTORS

In [3]:
def min_max_dist(*vectors):
    length = len(vectors) #how many vectors to begin with?
    dist_lst = [] #input the distance between vectors
    v_range = list(range(0, len(vectors))) #no of vectors to work with
    index = 0
    while index < length:
        for v in vectors:
            base_vector = vectors[0]
            distance = np.linalg.norm(base_vector-vectors[index]) #calculate vector distance
            dist_lst.append(distance)
            index += 1
    dist_lst.remove(0.0) #for instances when distance is vector by itself
    print(min(dist_lst), max(dist_lst))

vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
vec3 = np.array([7, 8, 9])
vec4 = np.array([10, 11, 12])
vec5 = np.array([13, 14, 15])

min_max_dist(vec1, vec2, vec3, vec4, vec5)
print()

min_max_dist(vec3, vec1)

5.196152422706632 20.784609690826528

10.392304845413264 10.392304845413264


EX10.9: IF ONE PAIR OF VECTORS IS PERPENDICULAR?

In [4]:
def any_normal(*vectors):
    length = len(vectors) #how many vectors to begin with?
    scar_prod_lst = [] #input the scalar product between vectors
    index = 0
    while index < length:
        for v in vectors:
            base_vector = vectors[0]
            scalar_product = np.dot(base_vector, vectors[index])
            scar_prod_lst.append(scalar_product)
            index += 1
    if 0 in scar_prod_lst:
        return True
    else:
        return False

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3, 4])
vec4 = np.array([-1, 5])

print(any_normal(vec1, vec2, vec3, vec4))
print(any_normal(vec2, vec3))

True
False


In [5]:
def any_normal(*vectors):
    for i in range(len(vectors)):
        for j in range(i + 1, len(vectors)):
            if np.dot(vectors[i], vectors[j]) == 0:
                return True
    return False

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3, 4])
vec4 = np.array([-1, 5])

print(any_normal(vec1, vec2, vec3, vec4))

True


EX10.10 and 10.11

In [6]:
def get_loto(num):
    population = np.arange(0, 101)
    rand_repeat_select = np.random.choice(population, size=(num, 5, 5), replace=True)
    print(rand_repeat_select)
    
get_loto(3)
print()


def get_unique_loto(num):
    population = np.arange(0, 101)
    rand_unique_select = np.random.choice(population, size=(num, 5, 5), replace=False)
    print(rand_unique_select)

get_unique_loto(2)
print()

[[[66 19 33 46 81]
  [78  7  8 99 29]
  [40 13 38 78 77]
  [62 99 88 59 82]
  [82 38 83 10 23]]

 [[80 51 75  0 31]
  [82 54  3  6 80]
  [60 46 38 20 25]
  [83 55 14  5 91]
  [91 63 68 56 90]]

 [[ 1 36 19 61 39]
  [77 62 83 52 48]
  [35 71 35 83 40]
  [ 2 75 29 32 54]
  [ 5  7  2 21 16]]]

[[[ 89  82  23  74  94]
  [ 10  12   9  33   2]
  [ 70  47  11  16 100]
  [  8  87  56  59  29]
  [ 86  96  36  60  28]]

 [[  5  35   7  18  31]
  [ 39  42  67  38  44]
  [ 53  34  55  24  64]
  [ 63  43  19  97  14]
  [ 80  54   6  57  84]]]



Exercise 10.11

In [7]:
def get_unique_loto(num):
    unique_loto = np.zeros((num, 5, 5), dtype=np.uint8)
    population = np.array(range(1, 101))
    for x in range(0, num):
        loto = np.random.choice(population, size=25, replace=False).reshape((5, 5))
        unique_loto[x] = loto
    return(unique_loto)

get_unique_loto(4)
print(np.shape(get_unique_loto(4)))

get_unique_loto(10)
print(np.shape(get_unique_loto(10)))

(4, 5, 5)
(10, 5, 5)
