In [2]:
import numpy as np
import pandas as pd

In [3]:
print('np.zeros helps to create an array of 0')
#np.zeros(shape, dtype=?)
x = np.zeros((2, 3), dtype=int)
print(x)
print()

y = np.zeros(4)
print(y)
print()


print('np.ones helps to create an array of 1')
#np.ones(shape, dtype=?)
x = np.ones((2, 2), dtype=int)
print(x)
print()

y = np.ones(3)
print(y)
print()


print('np.full creates an n-dimensional array of a random value')
#np.full(shape, fill_value=?, dtype=?)
x = np.full((2, 4), fill_value=3, dtype=int)
print(x)
print()

y = np.full(3, fill_value=7)
print(y)
print()


print('np.identity creates an identity matrix with specified dimensions')
#np.identity(n, dtype=None)

x = np.identity(3)
print(x)
print()

np.zeros helps to create an array of 0
[[0 0 0]
 [0 0 0]]

[0. 0. 0. 0.]

np.ones helps to create an array of 1
[[1 1]
 [1 1]]

[1. 1. 1.]

np.full creates an n-dimensional array of a random value
[[3 3 3 3]
 [3 3 3 3]]

[7 7 7]

np.identity creates an identity matrix with specified dimensions
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [4]:
print('min and max')
arr = np.array([1, 9, 0, 4])
min_val = np.min(arr)
max_val = np.max(arr)
print(min_val, max_val, sep='\n')
print()


print('count non-zero: count all the non-zero elements \
and return their count')
#np.count_nonzero(a, axis=None, *, keepdims=False)
a = np.array([0, 0, 6, 2, 0])
print(np.count_nonzero(a))
print()


print('argwhere: find and return all the index of non-zero elements')
#np.argwhere(?)
a = np.array([0, 0, 6, 0, 1])
print(np.argwhere(a))
print()


print('argmax returns the index of the max element from the array. \
It can be used to get the index of high probability predicted labels \
in multiclass image classification problems')
#np.argmax(?, axis=Mone, out=None)
arr = np.array([[0.12, 0.64, 0.19, 0.05]])
print(np.argmax(arr))
print()

print('argmin will return the index of the lowest element \
from the array.')
#np.argmin(?, axis=Mone, out=None)
print(np.argmin(arr))
print()

min and max
0
9

count non-zero: count all the non-zero elements and return their count
2

argwhere: find and return all the index of non-zero elements
[[2]
 [4]]

argmax returns the index of the max element from the array. It can be used to get the index of high probability predicted labels in multiclass image classification problems
1

argmin will return the index of the lowest element from the array.
3



In [5]:
print('sort: sort the array and return')
#np.sort(a, axis=-1, kind=None, order=None)

arr = np.array([2, 3, 1, 7, 4, 5])
s_arr = np.sort(arr)
print(s_arr)

sort: sort the array and return
[1 2 3 4 5 7]


In [6]:
print('abs: Return the absolute values of elements inside an array.\
It is useful when an array contains negative values.')
a = np.array([[1, -3, 4], [-2, -4, 3]])
print(np.abs(a))
print()

abs: Return the absolute values of elements inside an array.It is useful when an array contains negative values.
[[1 3 4]
 [2 4 3]]



In [7]:
print('copy to: copy the content of one array into another')
#copyto(dst, src, casting='same_kind', where=True)
#dst: array into which values are copied
#src: array from which values are copied

arr1 = np.array([2, 3])
arr2 = np.array([4, 5])
print(arr1, arr2, sep='\n')
print()

np.copyto(arr1, arr2) #just a function, doesn't print anything: None
print(arr1, arr2, sep='\n')
print()

copy to: copy the content of one array into another
[2 3]
[4 5]

[4 5]
[4 5]



In [8]:
print('np.intersect1d function returns all the unique values from \
both arrays in a sorted manner.')
#np.intersect1d(arr1, arr2, assume_unique=False, return_indices=False)

#assume_unique: if true, then input arrays are both assumed to be unique
#return_indices: if true, then common elements indices are returned

ar1 = np.array([2, 3, 4])
ar2 = np.array([3, 4, 8])
print(np.intersect1d(ar1, ar2))
print()


print('np.setdiff1d function returns all the unique elements from \
array 1 that are not present in arr2')

ar1 = np.array([2, 3, 4])
ar2 = np.array([3, 4, 8])
print(np.setdiff1d(ar1, ar2))
print()


print('setxor1d function will return all the unique values from both \
arrays in sorted order.')
a = np.array([1, 2, 3, 4, 6])
b = np.array([1, 4, 9, 4])
print(np.setxor1d(a, b))
print()


print('union1d function will combine both arrays into one')
x = np.array([2, 3, 7, 5])
y = np.array([8, 5, 4])
print(np.union1d(x, y))

np.intersect1d function returns all the unique values from both arrays in a sorted manner.
[3 4]

np.setdiff1d function returns all the unique elements from array 1 that are not present in arr2
[2]

setxor1d function will return all the unique values from both arrays in sorted order.
[2 3 6 9]

union1d function will combine both arrays into one
[2 3 4 5 7 8]


In [9]:
print('hstack will stack appends one array at the end of another')
a = np.array([1, 2, 3])
b = np.array([1, 4, 9])
print(np.hstack((a, b)))
print()

print('vstack will stack one array on top of another')
print(np.vstack((a, b)))
print()

hstack will stack appends one array at the end of another
[1 2 3 1 4 9]

vstack will stack one array on top of another
[[1 2 3]
 [1 4 9]]



In [10]:
print('np.allclose function finds whether two arrays are equal or approximately equal to each other based on some tolerance value if \
the shape of both arrays is the same.')
a = np.array([0.25, 0.4, 0.6, 0.32])
b = np.array([0.26, 0.3, 0.7, 0.32])
tolerance = 0.1 ## Total Difference 
print(np.allclose(a, b, tolerance))
print()
tolerance = 0.4 ## Total Difference 
print(np.allclose(a, b, tolerance))
print()

np.allclose function finds whether two arrays are equal or approximately equal to each other based on some tolerance value if the shape of both arrays is the same.
False

True



In [11]:
print('It is used to repeat elements of an array for n number of times')
#np.repeat(a, repeats, axis=None)
print(np.repeat('2017', 3))
print()
fruits = pd.DataFrame([
    ['Mango', 40],
    ['Apple', 90],
    ['Banana', 130]
],columns=['Product', 'Container Sales'])
print(fruits)
print()
fruits['Year'] = np.repeat(2020, fruits.shape[0])
print(fruits)
print()

It is used to repeat elements of an array for n number of times
['2017' '2017' '2017']

  Product  Container Sales
0   Mango               40
1   Apple               90
2  Banana              130

  Product  Container Sales  Year
0   Mango               40  2020
1   Apple               90  2020
2  Banana              130  2020



In [12]:
print('savetxt used to save the content of an array inside a text file.')
''' Generate array with 500 elements '''
arr = np.linspace(10, 100, 500).reshape(25, 20) 

##saves array data inside a txt File
np.savetxt('array.txt', arr)
print()

print('loadtxt used to load the content of an array from a text file. \
It takes the file name as a parameter')
#loads array data from a txt file
np.loadtxt('array.txt')
print()

savetxt used to save the content of an array inside a text file.

loadtxt used to load the content of an array from a text file. It takes the file name as a parameter

