In [1]:
import numpy as np

EXERCISE 8.5: DISTANCE BETWEEN TWO VECTORS > 100

In [2]:
a = np.array([23, 34, 27])
b = np.array([-54, 1, 46])
c = np.array([46, 68, 54])

d_ab = np.linalg.norm(a-b)
d_ac = np.linalg.norm(a-c)
d_bc = np.linalg.norm(b-c)

print(d_ab, d_ac, d_bc)

85.901105930017 49.13247398615299 120.6358155772986


EXERCISE 8.6: ANY SCALAR PRODUCT PAIRS

In [3]:
a = np.array([23, 34, 27])
b = np.array([-54, 1, 46])
c = np.array([46, 68, 54])

a_b = np.dot(a, b)
a_c = np.dot(a, c)
b_c = np.dot(b, c)

print(a_b, a_c, b_c)
print()

ab = np.sum(a*b)
ac = np.sum(a*c)
bc = np.sum(b*c)

print(ab, ac, bc)

34 4828 68

34 4828 68


EXERCISE 9.6

In [4]:
np.random.seed(2021)
simple = np.random.rand()
print(simple)
print()

randoms = np.random.uniform(-150, 2021, size=120)
print(randoms)
print()

table = np.random.randint(1, 101, size=(3,2))
print(table)
print()


np.random.seed(2021)
even = np.arange(2, 17, 2)
print(even)
print()
mix = np.random.permutation(even)
print(mix)
print()
select = np.random.choice(even, size=3, replace=False)
print(select)
print()
triplet = np.random.permutation(select)
print(triplet)
print()

0.6059782788074047

[ 1.44214488e+03  1.51654277e+02  5.28813265e+02  2.01501516e+03
  1.28240517e+02  2.38594033e+02  1.48460111e+03  1.28755048e+03
  1.55273730e+03  6.03577336e+01 -2.28417401e+01  1.93936169e+03
  1.18854621e+03  3.80736459e+01  1.06852230e+03  1.18847514e+03
  1.94250320e+03  1.09681462e+03  6.55790201e+02  8.31607324e+02
  2.88216888e+02  1.08596141e+03  2.73553360e+02  1.11722142e+03
  8.84076551e+02  9.74175063e+02  1.63694713e+03  1.43966053e+03
 -7.88273550e-02  1.30919192e+03  1.24700551e+03  1.64761920e+03
  2.93903055e+02  1.19056852e+03  1.19102890e+03  5.03619976e+02
  1.74254881e+03  1.13013901e+03  1.98142287e+03  8.10086179e+02
  1.24235695e+02  9.54671885e+02  7.87407805e+02  1.83850479e+03
  1.38927296e+03  1.78361285e+03  1.12847065e+03  1.23255777e+03
  5.92935602e+02  1.63845066e+03  5.12482326e+02  5.17676863e+02
  2.87071500e+02  4.25673103e+02  1.26315547e+03  1.85668749e+02
  6.93866612e+02  1.25597031e+03  1.69165738e+03 -1.14109610e+01
  7.4

In [5]:
arr = np.arange(8)
print(arr)
print()

arr.shape = (2, 4)
print(arr)
print()



arr = np.arange(6)
print(arr)
print()

arr_new = arr.reshape((2, 3))
print(arr_new)
print()



arr = np.arange(8)
arr.shape = (2, 4)
print(arr)
print()

arr_trans = arr.transpose()
print(arr_trans)
print()

arr_1 = np.arange(3)
print(arr_1.shape)
print()

arr1_trans = arr_1.transpose()
print(arr1_trans.shape)
print()



nd_array = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4)
print(nd_array)
print()

print('two elements from 3rd column:')
print(nd_array[:2, 2])
print()

print('all elements from 3rd column:')
print(nd_array[:, 2])
print()

('elements from 2nd line onwards, and last 2 elements:')
print(nd_array[1:, 2:4])

print()



nd_array = np.linspace(0, 6, 12, endpoint=False).reshape(3, 4)
print(nd_array)
print()

print('the last two elements starting the 2nd line:')
print(nd_array[1:, 2:])
print()

print(nd_array[:-1])
print()



arr = np.array([23, 12, 4, 15, 3])
arr_new = np.sort(arr)
print(arr)
print()

print(arr_new)
print()
print()



arr = np.array([22, 1, 10, 35])
print(arr.sort())
print(arr)
print()



data = np.array([4, 9, -4, 3])
roots = np.sqrt(data)
print(roots)
print()

which_is_nan = np.isnan(roots)
print(which_is_nan)
print()

print(roots[np.isnan(roots)])
print()

roots[np.isnan(roots)] = 0
print(roots)
print()

print(sum(roots))
print()



print(np.isnan(np.nan))
print()

[0 1 2 3 4 5 6 7]

[[0 1 2 3]
 [4 5 6 7]]

[0 1 2 3 4 5]

[[0 1 2]
 [3 4 5]]

[[0 1 2 3]
 [4 5 6 7]]

[[0 4]
 [1 5]
 [2 6]
 [3 7]]

(3,)

(3,)

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]

two elements from 3rd column:
[1. 3.]

all elements from 3rd column:
[1. 3. 5.]

[[3.  3.5]
 [5.  5.5]]

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]

the last two elements starting the 2nd line:
[[3.  3.5]
 [5.  5.5]]

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]]

[23 12  4 15  3]

[ 3  4 12 15 23]


None
[ 1 10 22 35]

[2.         3.                nan 1.73205081]

[False False  True False]

[nan]

[2.         3.         0.         1.73205081]

6.732050807568877

True



/var/folders/0j/pqz07rqd22q5j3qyrrpztqnr0000gn/T/ipykernel_65825/1180863003.py:91: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


EXERCISE 9.9.2

In [6]:
arr = np.arange(6)
print(arr)
print()

print(np.random.shuffle(arr))
print()

print(arr)
print()



playlist = ['Linkin Park', 'ACDC', 'Deep Purple']
print(playlist)
print()

shuffled = np.random.permutation(playlist)
print(shuffled)
print()

print(np.random.permutation(10))
print()



workers = ['Zlata', 'Yulia', 'Tanya M', 'Tanya V', 'Kristina']
unlucky_stay = np.random.choice(workers, size=1, replace=False)
print(unlucky_stay)
print()

unlucky_multiple = np.random.choice(workers, size=7, replace=True)
print(unlucky_multiple)
print()

choice = np.random.choice([1, 2, 3, 4, 5, 6], size=10)
print(choice)
print()



print(np.random.seed(23))
print(np.random.randint(10, size=(3,4)))
print()

np.random.seed(100)
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print(np.random.randint(10, size=3))
print()

[0 1 2 3 4 5]

None

[3 0 4 2 5 1]

['Linkin Park', 'ACDC', 'Deep Purple']

['Deep Purple' 'Linkin Park' 'ACDC']

[7 6 5 4 9 8 1 3 0 2]

['Tanya M']

['Tanya M' 'Yulia' 'Yulia' 'Tanya M' 'Tanya M' 'Kristina' 'Tanya M']

[4 2 3 3 1 3 5 6 4 4]

None
[[3 6 8 9]
 [6 8 7 9]
 [3 6 1 2]]

[8 8 3]
[7 7 0]
[4 2 5]



Exercise 9.9

In [7]:
print('vectors')
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
print(vec1 + vec2)
print()

print('lists')
lst1 = [2, 4, 7, 2.5]
lst2 = [12, 6, 3.6, 13]
print(lst1 + lst2)
print()

print('adding elements in lists')
print([x + y for x, y in zip(lst1, lst2)])



print('multiply by number')
vec = np.arange(5)
print(vec * 10)
print()

print('to the power off')
print(vec**2)
print()



vec = np.array([3, 4])
length = np.sqrt(np.sum(vec**2))
print(length)
print()

length_2 = np.linalg.norm(vec)
print(length_2)
print()



vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2)**2))
print(distance)
print()

distance_2 = np.linalg.norm(vec1 - vec2)
print(distance_2)
print()



vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
print(scalar_product)
print()



vec = np.array([2, 7, 18, 1])
print(vec.min())
print(np.max(vec))
print()

print(vec.mean())
print()

vectors
[14.  10.  10.6 15.5]

lists
[2, 4, 7, 2.5, 12, 6, 3.6, 13]

adding elements in lists
[14, 10, 10.6, 15.5]
multiply by number
[ 0 10 20 30 40]

to the power off
[ 0  1  4  9 16]

5.0

5.0

12.206555615733702

12.206555615733702

250.0

1
18

7.0

